### ISSUE TITLE
Estimation details error

### ISSUE THREAD

**Issue by todhunter** [estatic/estamation#3]
When I create estimation and click Save Im getting this error
Redmine 2.4.1 and Redmine 2.5.1 the same error

Started GET "/projects/sccd/estamations.%23%3C%23%3CClass:0x0000000426fe40%3E:0x007f28d032c558%3E" for 127.0.0.1 at 2014-04-24 11:13:00 +0200

ActionController::RoutingError (uninitialized constant EstamationController):
  activesupport (3.2.15) lib/active_support/inflector/methods.rb:230:in `block in constantize'
  activesupport (3.2.15) lib/active_support/inflector/methods.rb:229:in `each'
  activesupport (3.2.15) lib/active_support/inflector/methods.rb:229:in `constantize'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:69:in `controller_reference'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:32:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.15) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.15) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.15) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `_run__2651699089633481803__call__4328310994784449801__callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.15) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.15) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.15) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.15) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.15) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.15) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.15) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.15) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.15) lib/rails/engine.rb:484:in `call'
  railties (3.2.15) lib/rails/application.rb:231:in `call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.15) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /home/guesti/work/redmine/ruby/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /home/guest/work/redmine/ruby/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/guest/work/redmine/ruby/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by upanwar** [comment]
For me when i click on create ..it gives me the error - The page you are trying to view has been removed, but after refreshing it still goes onto create the particular listing. It just does not allow you to view it.

Any ideas

**Comment by estatic** [comment]
seems it fixed now
